### ISSUE TITLE
Create config file for each option

### ISSUE THREAD

**Issue by piebaker** [SmajloSlovakian/Minecraft-Smooth-Scrolling#1]
It would be excellent to have a config file for turning on/off each option, alongside more granular controls over speed / squish / acceleration etc

**Comment by SmajloSlovakian** [comment]
i've been looking into making a config file... i definitely plan on doing that but i can only make you be able to disable the animation or change the speed because of how i do the animation (i just divide the distance between where it's supposed to be and where it is basically)

**Comment by Taccnien** [comment]
Hi, I would love to be able to disable scrolling on hotbar. That´s the only thing making me not use the mod.

**Comment by SmajloSlovakian** [comment]
you can now tweak the speed of the animations and also disable them by setting the speed value to 0 as of 1.5.0...
