### ISSUE TITLE
the hotbar scrolls incorrectly

### ISSUE THREAD

**Issue by ItzPiligrim** [SmajloSlovakian/Minecraft-Smooth-Scrolling#12]
https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/140744428/4ac2e5b7-db68-47f2-981b-d1a0790fc649

**Comment by SmajloSlovakian** [comment]
can i have more information? what mods do you have installed and their versions, how does it behave when you scroll-over (going from last to first hotbar), what are your settings of the mod (located in .minecraft/config/smoothscroll.json)?

**Comment by SmajloSlovakian** [comment]
i have updated the hotbar smooth scrolling code a bit so maybe check out if it's still an issue in 1.9.0 if you're reading this... i'll close this issue and reopen if i get a response from you
