### ISSUE TITLE
Support for Chat Heads

### ISSUE THREAD

**Issue by pyj-pd** [SmajloSlovakian/Minecraft-Smooth-Scrolling#2]
[Chat Heads](https://modrinth.com/mod/chat-heads) is a Fabric mod which shows head image of the sender on left side of the chat. However, when used with this mod, the smooth scroll doesn't apply to the heads, causing heads and chats move separately, not smoothly.

**Comment by SmajloSlovakian** [comment]
well... the smooth scrolling worked in a way... but i have now fixed it... i hope it doesn't become a hell to maintain as i'm a modding noob right now

fixed in 1.6.0
