### ISSUE TITLE
2.0.0 incompatible with ChatHeads

### ISSUE THREAD

**Issue by MATRIX-feather** [SmajloSlovakian/Minecraft-Smooth-Scrolling#25]
### Description
When Smooth Scrolling 2.0.0 is installed alongside Chat Heads, the mixin of Chat Heads fails to apply and leads to a crash when using tab-complete for player names.

### Crash log
[crash-2024-04-14_23.57.17-client.txt](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/14971300/crash-2024-04-14_23.57.17-client.txt)

### Mods
- Fabric API
- Chat Heads
- Smooth Scrolling

**Comment by SmajloSlovakian** [comment]
okay so this happens because i replace a draw call with mine so that immediately fast doesn't break the masking by batching the command... i have some fixes on my mind, gonna try them out

**Comment by SmajloSlovakian** [comment]
Fixed in 2.0.1
