### ISSUE TITLE
The hotbar selector top get cut with Raised mod

### ISSUE THREAD

**Issue by MidyGamy** [SmajloSlovakian/Minecraft-Smooth-Scrolling#28]
Yeah the selector is cut when using the [Raised](https://modrinth.com/mod/raised) mod...
![image](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/95078425/2c243a85-06aa-4268-b66f-d5835c4b3967)

**Comment by MidyGamy** [comment]
![image](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/95078425/e466c3dc-7e0f-49a4-877e-7226726c6eb6)

**Comment by MidyGamy** [comment]
Maybe that can help
https://github.com/yurisuika/Raised/wiki/Compatibility#adding-compatibility

**Comment by SmajloSlovakian** [comment]
ok, i'll look at it

**Comment by SmajloSlovakian** [comment]
fixed mask when the chat or hotbar are raised with this mod... there is a minor issue however that i couldn't fix for whatever reason and it's that the lowest line of pixels is instantly scrolling (it's drawn by the mod) and i don't really have control over that
fixed in 2.0.2
