### ISSUE TITLE
ImmeditalyFast introduces issues with certain resourcepacks featuring core shaders

### ISSUE THREAD

**Issue by ItsPasi** [SmajloSlovakian/Minecraft-Smooth-Scrolling#32]
Since version 2.0.1, playing on the server MCCIsland will break the client and cause many visual glitches when another mod called ImmeditalyFast is also installed.

Playing either without ImmeditalyFast or playing with it but having version 2.0.0 or earlier of Smooth-Scrolling installed, will resolve the issue.

**Comment by SmajloSlovakian** [comment]
i've also encountered this issue but as i don't even have access to their resourcepack, i don't know what's happening there and i will have to ask for help on this one... (also, i don't want to go back to that way of working around it)

**Comment by ItsPasi** [comment]
Well I extracted the pack and can tell you at least that the shader folder of the pack causes the issue. I have no idea how to find the exact problem though.

[Resourcepack.zip](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/15130454/MCCIsland.Resourcepack.zip)

**Comment by SmajloSlovakian** [comment]
well now i wanna know how you did that... when i try to open the resourcepack as a zip inside the .minecraft/downloads folder, it gives me an error with multiple zip openers...

**Comment by ItsPasi** [comment]
> well now i wanna know how you did that... when i try to open the resourcepack as a zip inside the .minecraft/downloads folder, it gives me an error with multiple zip openers...

I used this program https://github.com/Speedy11CZ/mcrpx

**Comment by SmajloSlovakian** [comment]
this issue seems really inconsistent... right now it works as expected (except some other irrelevant issues)... sometimes it seems to not work as much... i really don't know what's happening (but yes it is most definitely due to the core shaders)

i'll set this to help wanted as i think that i won't be able to fix it myself

**Comment by SmajloSlovakian** [comment]
hi... can you test it out with the latest versions of this mod and immediately fast?

**Comment by ItsPasi** [comment]
Yes, I tried it out on a fresh 1.20.6 install with those mods and everything worked like it should :)

**Comment by TheCrossCarrier** [comment]
@SmajloSlovakian Hello. Could you add this fix to 1.20.4, please?

**Comment by SmajloSlovakian** [comment]
@TheCrossCarrier maybe when i get to it... but it will be a sort of hotfix type of version, i won't be backporting the new versions to 1.20.4- anymore

**Comment by SmajloSlovakian** [comment]
@TheCrossCarrier backported to minecraft version 1.20.1 and 1.20.4 in version 2.0.2-patch1 of the mod

**Comment by TheCrossCarrier** [comment]
@SmajloSlovakian I love you brother <3 Thanks a lot!
