### ISSUE TITLE
Incompatible with Raised Mod on forge with sinytra

### ISSUE THREAD

**Issue by LocChsNgu** [SmajloSlovakian/Minecraft-Smooth-Scrolling#34]
![image](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/119783501/64d9e88c-9d04-47d5-b8d3-45adad350f32)
So I came across a glitch that whenever I raise the HUD height, both chat and hotbar selector don't sync with the main hotbar
I used the Sinytra connector mod to use the Raised mod (Forge) and Smooth Scrolling (Frabic) at the same time as I cannot use Raised in Frabic also.

**Comment by SmajloSlovakian** [comment]
have you tried running the fabric version of the raised mod with your setup? i don't know if i'll be able to fix this with the forge version of the mod

**Comment by Novaenia** [comment]
> have you tried running the fabric version of the raised mod with your setup? i don't know if i'll be able to fix this with the forge version of the mod

The Fabric version of Raised for 24w10a also runs on 1.20.6 & this mod works nearly perfectly with it, but the bottom row of the selector isn't smooth:
![](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/80987908/80979e96-96c8-4b5a-80c8-6959916810fe)
EDIT: enabling Texture support in Raised options seems to fix this

**Comment by SmajloSlovakian** [comment]
yes that's a known bug which i don't know how to fix...

as you can work around this compatibility issue and making it compatible with this edge case is difficult, i'll consider this issue as won't fix and close it
