### ISSUE TITLE
Log Spam from smooth scrolling?

### ISSUE THREAD

**Issue by SabrCat** [SmajloSlovakian/Minecraft-Smooth-Scrolling#35]
I'm building a modpack which includes smooth scroll, and I noticed that every second the mod Smooth Scrolling sends "60" in the console. This does seem to be a bug. 
Here's a log:
[ViCaTdn.txt](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/15314118/ViCaTdn.txt)
What mod is sending it is only visible thanks to the Better Log4j Config mod. 
I do hope I identified the right mod to make an issue at.
Thanks in advance for giving this a look!

**Comment by SmajloSlovakian** [comment]
which version of smooth scroll do you use and on which minecraft version?

**Comment by SabrCat** [comment]
As it is stated in the log my mc version is 1.20.1 fabric loader 1.15.10 with mod version 2.0.2

**Comment by SmajloSlovakian** [comment]
XD sorry that it didn't occur to me that the version is in the log
ok, now i see the line printing things out... i'll make a hotfix for that version along with immediately fast compatibility improvements to 1.20.1 and 1.20.4

**Comment by SabrCat** [comment]
alright, thank you! If you don't mind, please do leave a comment here when a modrinth release of the hotfix is ready. I plan to launch my server tomorrow and am running a bit tight on time.

**Comment by SmajloSlovakian** [comment]
fixed in version 2.0.2-patch1 while (i think) not being present in newer versions

**Comment by SabrCat** [comment]
awesome! prism didn't recognize -patch1 as a higher version, but deleting and redownloading the mod selected the right version. Thanks for the update
