### ISSUE TITLE
Partially incompatible with HighLightItem and Item Borders

### ISSUE THREAD

**Issue by Novaenia** [SmajloSlovakian/Minecraft-Smooth-Scrolling#36]
elements added by [HighLightItem](https://modrinth.com/mod/d5BXxnVG) and [Item Borders](https://modrinth.com/mod/b1fMg6sH) don't scroll smoothly
![au4nH9](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/80987908/c0d69add-30b1-4faa-b697-f1cf189cce64)

**Comment by SmajloSlovakian** [comment]
i have now fixed the regular item highlighting to follow the scrolling as well... this doesn't mean that the compatibility with these mods is fixed... however, i have added two object shares for the other developers to use... i'm going to make an issue report to them in the near future... all of this will be backported to 1.20.1 and 1.20.4 along with 1.20.5

**Comment by SmajloSlovakian** [comment]
i managed to fix it on item borders by mixing into the mod... however, i don't think i will be so lucky with the other mod

**Comment by SmajloSlovakian** [comment]
i have opened a pull request in the highlightitem repository, which should fix the compatibility issues with my mod and now i'm just waiting for the developer to respond and/or merge

**Comment by SmajloSlovakian** [comment]
the highlightitem mod developer wants to change their approach to doing stuff which should fix the incompatibility. they however don't have any plans to backport them from 1.21

**Comment by SmajloSlovakian** [comment]
i'm going to close this issue as i have done everything i can do and the highlightitem compatibility fix is up to the other developer...
fixed in 2.1.0

**Comment by SmajloSlovakian** [comment]
compatibility with highlightitem will be released shortly... as i said, the highlightitem developer doesn't have plans to backport any changes to lower versions so it will only be compatible in 1.21+
