### ISSUE TITLE
The cursor position will cause the command line to flicker

### ISSUE THREAD

**Issue by EtherealAirRhyme** [SmajloSlovakian/Minecraft-Smooth-Scrolling#38]
Unfortunately, I cannot determine what mod caused it. When I try to disable all mods related to chat bar rendering, it still appears.
And it seems that it is not caused by a single mod. When I disable a mod, it disappears, but when I enable that mod again and try to reproduce it, it does not appear
This is the mod I use, version 1.20.4

https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/126517617/235543fc-2baa-4acd-89ed-9fd588b26551

[mods.zip.001.zip](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/15380420/mods.zip.001.zip)
[mods.zip.002.zip](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/15380424/mods.zip.002.zip)
[mods.zip.003.zip](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/15380422/mods.zip.003.zip)
[mods.zip.004.zip](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/files/15380421/mods.zip.004.zip)

Please remove .zip suffix

**Comment by SmajloSlovakian** [comment]
can you please try to reproduce it with the enable mask debug option turned on? you can find the config file in .minecraft/config/smoothscroll.json

**Comment by EtherealAirRhyme** [comment]
> can you please try to reproduce it with the enable mask debug option turned on? you can find the config file in .minecraft/config/smoothscroll.json

Thank you, I changed the false value of "enableMaskDebug" to true, but it still appears in these modules

**Comment by EtherealAirRhyme** [comment]
> 您能否尝试在打开“启用掩码调试”选项的情况下重现它？您可以在 .minecraft/config/smoothscroll.json 中找到配置文件

Thank you, I changed the false value of "enableMaskDebug" to true, but it still appears in these modules

Uploading 2024-05-22_07-43-17.mp4…

Uploading 2024-05-22_07-43-17.mp4…

Can I provide any other documents that can help you?

**Comment by EtherealAirRhyme** [comment]
> can you please try to reproduce it with the enable mask debug option turned on? you can find the config file in .minecraft/config/smoothscroll.json

Thank you, I changed the false value of "enableMaskDebug" to true, but it still appears in these modules

https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/126517617/a2d1909d-be34-4438-b005-25249c79a265

Do I have any other documents that can be helpful to you?

**Comment by SmajloSlovakian** [comment]
okay i think that this isn't a problem introduced by this mod... you haven't mentioned trying to reproduce it just without smooth scrolling, you can also try that but otherwise you just have to try to figure out which mods are causing the issues...

**Comment by EtherealAirRhyme** [comment]
> 好吧，我认为这不是这个模组引入的问题......您没有提到尝试在没有平滑滚动的情况下重现它，您也可以尝试一下，但除此之外，您只需要尝试找出导致问题的模组......

**Comment by EtherealAirRhyme** [comment]
> okay i think that this isn't a problem introduced by this mod... you haven't mentioned trying to reproduce it just without smooth scrolling, you can also try that but otherwise you just have to try to figure out which mods are causing the issues...

Great, thank you. I have identified the issue and found that it is caused by the "ImmediacelyFast" module. When I use it with Smooth Scroll, the background of the chat bar will flash

**Comment by EtherealAirRhyme** [comment]
If I set the "hud_matching" of this module to false, this problem will not occur;)

**Comment by SmajloSlovakian** [comment]
does it happen only with immediately fast and smooth scroll? if not, you should find the third mod causing this

**Comment by EtherealAirRhyme** [comment]
I'm not sure......From the results, as long as the ImmediacelyFast module is not added or the hud_matching option is turned off, it will not disrupt the work of the Smooth Scroll
