### ISSUE TITLE
Bug: inventory slided down and cause items not to show up.

### ISSUE THREAD

**Issue by HyPeRXKo** [SmajloSlovakian/Minecraft-Smooth-Scrolling#4]
When you use the survival inventory (normal/creative tab) because of this mod, the items textures are slided down, and makes them invisible in the hotbar (the hotbar is filled on the screenshot) and partially (10%) visible in the armor slots

![image_2023-11-11_070811071](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/47679671/cae187ff-025b-4275-9d79-c8263a8bfc70)

**Comment by SmajloSlovakian** [comment]
ooh that's a strange one! that happens because of the mask that makes scrolling in the creative tabs nicer... i'll fix that when i'll have time

**Comment by SmajloSlovakian** [comment]
Fixed in 1.7.1
