### ISSUE TITLE
1.21 Crash

### ISSUE THREAD

**Issue by Pie-Not-Lie** [SmajloSlovakian/Minecraft-Smooth-Scrolling#41]
Crash on startup when using the latest 1.21 build.

Fabric 0.15.11, only mods used were Smooth Scrolling and Fabric API

**Comment by SmajloSlovakian** [comment]
fixed now... but i don't understand how did it even occur... like... i built it for 1.21-rc1 and it crashes and when i built it for 1.21 it doesn't crash... there should be like no differences

**Comment by Pie-Not-Lie** [comment]
I'm with you on this one...but thanks! :D
