### ISSUE TITLE
[Incompatibility] Creative menu search has an issue when using the Sounds mod.

### ISSUE THREAD

**Issue by slushieuwu** [SmajloSlovakian/Minecraft-Smooth-Scrolling#46]
When using the [Sounds](https://modrinth.com/mod/sound) mod, whenever the creative search menu is filled to the last line, there is a nonstop scroll sound.

For example when searching "cre":

https://github.com/user-attachments/assets/fedf2a96-aa06-4588-86cc-7a7b0ab43d3a

When searching "woo":

https://github.com/user-attachments/assets/f9b24342-debe-4cca-b5ba-4e057b749164

**Comment by slushieuwu** [comment]
it appears the dev of the sounds mod said they were going to contact you, sorry if they already did :p

**Comment by SmajloSlovakian** [comment]
they didn't yet... i'm going to investigate the issue and see what can be done by me and/or them

**Comment by SmajloSlovakian** [comment]
ok so i don't know why it spams scrollItems() only when there are exactly 5 rows of items in the tab... i use scrollitems() to update the slots so the correct items show up there at correct times so it should be clicking almost always when you have scrolled at least once without changing tabs / search filter but not when stationary as the sounds mod does check if the scroll position is the same as before or not... gonna look into it more later

**Comment by SmajloSlovakian** [comment]
this is now fixed... it isn't perfect but at least it isn't annoying (i think)... further fixing would be a bit hard, so i'm marking this as fixed

**Comment by SmajloSlovakian** [comment]
partially resolved in update 2.1.3... no further resolving will be done
