### ISSUE TITLE
Error in ide 

### ISSUE THREAD

**Issue by SpigotRCE** [SmajloSlovakian/Minecraft-Smooth-Scrolling#47]
ChatHudMixin#demask throws error "Method parameters do not match expected parameters for ModifyVariable", "Expected return type 'ChatHud' for ModifyVariable method"
![image](https://github.com/user-attachments/assets/1fb9e724-3d5a-43cc-b2cf-ee7d2ed3908d)

**Comment by SmajloSlovakian** [comment]
if you changed nothing, idk how it sees an error there as it works for me as it was built and published... did you try to build or run? it sometimes fixes stuff like this for me

**Comment by SpigotRCE** [comment]
Wait, it compiles and runs perfectly but idk why it shows error in ide

**Comment by SmajloSlovakian** [comment]
i have these unexplained errors in my ide sometimes too and it's so annoying... i wish i knew of a permanent fix...
