### ISSUE TITLE
[Incompatibility] Crash with Condensed Creative

### ISSUE THREAD

**Issue by MidyGamy** [SmajloSlovakian/Minecraft-Smooth-Scrolling#48]
The games crashes when you open the creative inventory with the [Condensed Creative](https://modrinth.com/mod/condensed-creative) mod...

**Comment by MidyGamy** [comment]
I also oppened an issue on their issue report
https://github.com/wisp-forest/condensed-creative/issues/18

**Comment by SmajloSlovakian** [comment]
crashing resolved in update 2.1.3... other issues are either resolved or partially resolved... remaining issues are minor and should be fixed by the developer of the other mod... there is one extremely minor issue i don't expect the developer to fix...
