### ISSUE TITLE
ModMenu's mod list cannot scroll 

### ISSUE THREAD

**Issue by FlameFire26** [SmajloSlovakian/Minecraft-Smooth-Scrolling#5]
Mods:
- 3dskinlayers-fabric-1.5.6-mc1.20.2
- fabric-api-0.91.1+1.20.4
- fabric-language-kotlin-1.10.16+kotlin.1.9.21
- I18nUpdateMod-3.5.2-all
- modmenu-9.0.0-pre.1
- smoothscroll-1.8.1-1.20.1-4

Note:
- Some mods are just to make up the number for the list to scroll. They might almost impossible to cause this issue.
- No problems have been found in vanilla or other lists so far.
- I'm not sure whether I should report here or to ModMenu.

Game:
- Minecraft 1.20.4 Fabric

**Comment by SmajloSlovakian** [comment]
thanks for the report, i'll try to reproduce and fix it in the near future

**Comment by SmajloSlovakian** [comment]
for now, you can still scroll using the scrollbar
