### ISSUE TITLE
2.1.3 for 1.20.1 crashes when using Java 17

### ISSUE THREAD

**Issue by pajicadvance** [SmajloSlovakian/Minecraft-Smooth-Scrolling#53]
https://mclo.gs/XBbGkpo

**Comment by Mortycio** [comment]
same here

https://gnomebot.dev/paste/254806806516203520/1283143972847484969/1283143972914466887

**Comment by SmajloSlovakian** [comment]
i've now marked that version as alpha and i will work on this issue tomorrow... for now, please use the older version of the mod

**Comment by Mortycio** [comment]
@pajicadvance 2.1.2 works fine, we can use that while waiting for a fix

**Comment by SmajloSlovakian** [comment]
this issue should be fixed on 2.1.3.1... please let me know if it has been in fact fixed (i have tested it on java 17 but just to make sure)

**Comment by Mortycio** [comment]
It works fine! Thanks 😄
