### ISSUE TITLE
Hotbar incompatibility with Exordium

### ISSUE THREAD

**Issue by BK49YT** [SmajloSlovakian/Minecraft-Smooth-Scrolling#55]
![ezgif-6-efc9262bc2](https://github.com/user-attachments/assets/ca763a75-ce02-4acf-bc6e-967013b6ff44)

- Smooth Scrolling Ver. 2.1.3
- Minecraft Ver. 1.21
- I have over 140 Mods installed so its hard to type them all out so here's a txt file
[VMC Enhanced Mods.txt](https://github.com/user-attachments/files/17086006/VMC.Enhanced.Mods.txt)
- Just loading up Minecraft will reproduce the the problem
- The scrolling seems to be not on track with the hotbar squares and seems to just have a mind of its own.

**Comment by SmajloSlovakian** [comment]
the hotbar (or any other element my mod interacts with) has to be rerendered every frame if you want it to be smooth... you have a mod, which rerenders the hotbar only when you switch slots and so my mod just moves the indicator, renders it but then it moves it but doesn't render and repeats until you switch slots again...

i don't know every mod you have but it is probably exordium as it limits the framerate of certain gui elements... except it does that at fixed framerate and doesn't just rerender the hotbar only when you change slot so idk about that but it definitely doesn't help... if that doesn't help, you can use binary search to identify which mod is causing issues... if you don't know what that is then here is a guide... it's really quite simple
<details>
<summary>How to binary search</summary>
<br>
A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.

Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.

Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods like Fabric API out of order.

By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.
</details>

**Comment by KelpPat** [comment]
im not the same person that reported the issue, but deleting exordium did help fix the same problem i had.
