### ISSUE TITLE
Raised mod is incompatible again

### ISSUE THREAD

**Issue by iv8512** [SmajloSlovakian/Minecraft-Smooth-Scrolling#56]
Would support for Raised (https://modrinth.com/mod/raised) be possible? The bottom row of pixels are not being smooth.

**Comment by SmajloSlovakian** [comment]
raised is almost fully compatible with smooth scrolling by making it compatible aside from that one small quirk... i don't know how to fix that but i will look into it again as i haven't done that since forever

**Comment by SmajloSlovakian** [comment]
ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh they have recently added an api and removed the simple fabric object share thing i used to make my mod compatible.... why??? i don't like to implement so many mods just to make them at least sort of compatible

**Comment by iv8512** [comment]
Just found out that if you change the texture setting to "Replace" in Raised, it fixes the issue.

**Comment by SmajloSlovakian** [comment]
fixed in 2.2.0
