### ISSUE TITLE
Hotbar wrong

### ISSUE THREAD

**Issue by AntiBlaze1** [SmajloSlovakian/Minecraft-Smooth-Scrolling#57]
Hotbar completely wrong when using number keys to select.

**Comment by SmajloSlovakian** [comment]
do you use any other mods? and can you explain what exactly is wrong?

**Comment by AntiBlaze1** [comment]
> do you use any other mods? and can you explain what exactly is wrong?

yes, a lot. For now i disabled the mod for hotbar and chat. 
issue might be caused by exordium

**Comment by SmajloSlovakian** [comment]
yeah that mod is problematic... i think that if that's the issue and you have more info, you can add to the issue that's already here... if you figure out that it's a different issue, you can post a comment here and i'll reopen the issue
