### ISSUE TITLE
Log spam in the newest version

### ISSUE THREAD

**Issue by UninenVille** [SmajloSlovakian/Minecraft-Smooth-Scrolling#64]
Seems like you've forgotted to remove this:
https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/blob/3f5e692303293d4edba24faaf271b03d1be4bfb3/src/main/java/smsk/smoothscroll/mixin/Chat/ChatHudMixin.java#L97

**Comment by SmajloSlovakian** [comment]
thanks! didn't notice... imma fix it today

**Comment by SmajloSlovakian** [comment]
forgot to close the issue... dixed in 2.2.1.1
