### ISSUE TITLE
Chat scrolling bug when using smooth scrolling with chat patches

### ISSUE THREAD

**Issue by UniOnHeikoil** [SmajloSlovakian/Minecraft-Smooth-Scrolling#7]
When opening chat it scrolls from up to down as shown in the video below. I'm using Minecraft 1.20.4, Fabric Loader 0.15.1
and following mods:
- chatpatches 204.6.1
- fabric-api 0.91.3+1.20.4
- smoothscroll 1.8.2

Video of the bug:
https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/135575164/5e6be236-5cca-44e6-abf6-bd46ea9e91b4

If you want i can create issue in chatpatches gh repo too.

**Comment by SmajloSlovakian** [comment]
hi, sorry for the late reply... there also seems to be an issue with the chat being moved upwards by those 10 px... i'll look at it when i have time

**Comment by SmajloSlovakian** [comment]
Masking issue fixed in Chat Patches 204.6.2 with Smooth Scroll 1.8.3
Chat opening issue fixed in Smooth Scroll 1.8.3
